package ctrl.nazarov.bot.enums;

public enum Step {
    MAIN,

    PROFILE_ENTER, PROFILE_ENTER_NAME, PROFILE_ENTER_PHONE, PROFILE_EDIT, PROFILE_EDIT_PHONE, PROFILE_EDIT_NAME,

    //admin
    POST_SEND, ORDER, REGION_NAME,
}
